version: "3.8"
services:
  web-fe:
    image: brunocs90/gsd:swarm-stack
    command: python app.py
    deploy:
      replicas: 25
    ports:
      - target: 8080
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"
    networks:
      counter-net:


networks:
  counter-net:


volumes:
  counter-vol:
